/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form.usluga;

import form.components.TableModelUsluga;
import controller.ClientController;
import domain.Usluga;
import form.FrmMain;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandra
 */
public class FrmFindUsluga extends javax.swing.JDialog {

    /** Creates new form FrmFindUsluga */
    public FrmFindUsluga(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretrazi usluge");
        
        TableModelUsluga tmUsluga= new TableModelUsluga();
        Thread thread=new Thread(tmUsluga);
        thread.start();
        tblUsluga.setModel(tmUsluga);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPretraga = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsluga = new javax.swing.JTable();
        btnAzurirajUslugu = new javax.swing.JButton();
        btnObrisiUslugu = new javax.swing.JButton();
        btnIzmeniUslugu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        tblUsluga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblUsluga);

        btnAzurirajUslugu.setText("Produži zaduženje");
        btnAzurirajUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzurirajUsluguActionPerformed(evt);
            }
        });

        btnObrisiUslugu.setText("Obriši uslugu");
        btnObrisiUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiUsluguActionPerformed(evt);
            }
        });

        btnIzmeniUslugu.setText("Izmeni uslugu");
        btnIzmeniUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniUsluguActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(txtPretraga)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIzmeniUslugu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAzurirajUslugu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnObrisiUslugu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAzurirajUslugu)
                    .addComponent(btnObrisiUslugu)
                    .addComponent(btnIzmeniUslugu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAzurirajUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzurirajUsluguActionPerformed
        int rowIndex=tblUsluga.getSelectedRow();
        if(rowIndex>=0){
            try {
                SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yyyy");
                TableModelUsluga tm=(TableModelUsluga) tblUsluga.getModel();
                Usluga usluga= tm.getUsluga(rowIndex);
                Calendar calendar = Calendar.getInstance();
                Date date = usluga.getDatumIsteka(); 
                
                long razlika= (date.getTime()-usluga.getDatumIzdavanja().getTime())/(1000*60*60*24);
                System.out.println(razlika);
                if(razlika>=40){
                     JOptionPane.showMessageDialog(this,
                            "Zaduzenje ne moze biti produzeno vise od jedanput","Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                calendar.setTime(date);
                int daysToAdd = 20;
                calendar.add(Calendar.DAY_OF_MONTH, daysToAdd); 
                Date newDate = calendar.getTime();
                
                
                
                usluga.setDatumIsteka(newDate);
                

                ClientController.getInstance().updateUsluga(usluga);
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Niste odabrali nijednu uslugu","Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAzurirajUsluguActionPerformed

    private void btnObrisiUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiUsluguActionPerformed
        TableModelUsluga tm = (TableModelUsluga) tblUsluga.getModel();
        int rowIndex = tblUsluga.getSelectedRow();
        if (rowIndex >= 0) {
            int deleteYesNo = JOptionPane.showConfirmDialog(this,
                    "Da li ste sigurni da zelite da obrisete ovu uslugu?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

            if (deleteYesNo == JOptionPane.NO_OPTION) {
                return;
            }

            if (deleteYesNo == JOptionPane.YES_OPTION) {
                try {
                    Usluga usluga = tm.getUsluga(rowIndex);
                    /*ArrayList<StavkaUsluge> listaStavki = 
                            (ArrayList<StavkaUsluge>) ClientController.getInstance().getAllStavkeUsluge(usluga);
                    System.out.println(listaStavki);
                    for (StavkaUsluge stavkaUsluge : listaStavki) {
                        try {
                            Knjiga knjiga = stavkaUsluge.getKnjiga();
                            
                            knjiga.setKolicina(knjiga.getKolicina() + 1);
                            System.out.println(knjiga.getNaziv());
                            System.out.println(knjiga.getKolicina());
                            System.out.println(knjiga.getZanr());
                            System.out.println(knjiga.getAutor());
                            ClientController.getInstance().updateKnjiga(knjiga);
                        } catch (Exception ex) {
                            Logger.getLogger(FrmFindUsluga.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }*/
                    ClientController.getInstance().deleteUsluga(usluga);
                    refreshTable();
                    FrmMain main=new FrmMain();
                    main.refreshTableKnjiga();
                    //TableModelKnjiga tmKnjiga= new TableModelKnjiga();
                    //tmKnjiga.povecajKolicinu(knjiga);
                    JOptionPane.showMessageDialog(this, "Sistem je obrisao uslugu");
                } catch (Exception ex) {
                    Logger.getLogger(FrmFindUsluga.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise uslugu", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnObrisiUsluguActionPerformed

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased
        String parametar=txtPretraga.getText();
        TableModelUsluga tmUsluga= (TableModelUsluga)tblUsluga.getModel();
            tmUsluga.setParametar(parametar);
            if(tmUsluga.getRowCount()==0){
                JOptionPane.showMessageDialog(this,
                        "Sistem ne moze da nadje usluge po zadatoj vrednosti",
                        "Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
    }//GEN-LAST:event_txtPretragaKeyReleased

    private void btnIzmeniUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniUsluguActionPerformed
        int rowIndex=tblUsluga.getSelectedRow();
        if(rowIndex>=0){
            try {
                TableModelUsluga tm=(TableModelUsluga) tblUsluga.getModel();
                Usluga usluga= ClientController.getInstance().getUsluga(tm.getUsluga(rowIndex));
                JOptionPane.showMessageDialog(this,"Sistem je ucitao uslugu.");
                new FrmUpdateUsluga(this, true,usluga).setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FrmFindUsluga.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Sistem ne moze da ucita uslugu","Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniUsluguActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFindUsluga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFindUsluga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFindUsluga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFindUsluga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmFindUsluga dialog = new FrmFindUsluga(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzurirajUslugu;
    private javax.swing.JButton btnIzmeniUslugu;
    private javax.swing.JButton btnObrisiUslugu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblUsluga;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    public void refreshTable() {
        TableModelUsluga tmUsluga= (TableModelUsluga) tblUsluga.getModel();
        tmUsluga.refreshTable();
    }

}
