/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.usluga;

import communication.Communication;
import controller.ClientController;
import domain.Bibliotekar;
import domain.Korisnik;
import domain.Usluga;
import domain.Knjiga;
import domain.StavkaUsluge;
import form.components.TableModelKorisnik;
import form.components.TableModelStavke;
import form.components.TableModelKnjiga;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandra
 */
public class FrmUpdateUsluga extends javax.swing.JDialog {
    Bibliotekar ulogovani;
    Knjiga knjiga;
    Korisnik korisnik;
    Usluga usluga;
    /**
     * Creates new form FrmUpdateUsluga
     */
    public FrmUpdateUsluga(java.awt.Dialog parent, boolean modal, Usluga usluga) {
        super(parent, modal);
        try {
            initComponents();
            setLocationRelativeTo(null);
            setTitle("Izmeni uslugu");
            
            this.usluga=usluga;
            this.korisnik=usluga.getKorisnik();
            this.ulogovani= Communication.getInstance().getUlogovani();
            lblUlogovani.setText("Ulogovani: "+ulogovani);
            prepareView();
            
        } catch (Exception ex) {
            Logger.getLogger(FrmUpdateUsluga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDatumOd = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDatumDo = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKorisnik = new javax.swing.JTable();
        txtKorisnik = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeUsluge = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtKnjiga = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKnjiga = new javax.swing.JTable();
        btnIzmeniUslugu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblUlogovani.setText("Ulogovani:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usluga"));

        jLabel1.setText("Izabrani korisnik:");

        jLabel3.setText("Datum od:");

        txtDatumOd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat(""))));

        jLabel4.setText("Datum do:");

        txtDatumDo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga korisnika"));

        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        tblKorisnik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKorisnik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKorisnikMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKorisnik);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtPretraga)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavka usluge"));

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Obrisi stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        tblStavkeUsluge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkeUsluge);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga knjige"));

        txtKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKnjigaActionPerformed(evt);
            }
        });
        txtKnjiga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKnjigaKeyReleased(evt);
            }
        });

        tblKnjiga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblKnjiga);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKnjiga, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajStavku)
                    .addComponent(btnObrisiStavku))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnDodajStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisiStavku)
                        .addGap(31, 31, 31))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKorisnik)
                            .addComponent(txtDatumDo)
                            .addComponent(txtDatumOd))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(73, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnIzmeniUslugu.setText("Sacuvaj uslugu");
        btnIzmeniUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniUsluguActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUlogovani)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(btnIzmeniUslugu, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeniUslugu)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased
        String parametar = txtPretraga.getText();
        TableModelKorisnik tmKorisnik = (TableModelKorisnik) tblKorisnik.getModel();
        tmKorisnik.setParametar(parametar);
        if (tmKorisnik.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Sistem ne moze da nadje korisnike po zadatoj vrednosti",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_txtPretragaKeyReleased

    private void tblKorisnikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKorisnikMouseClicked
        int selectedRow=tblKorisnik.getSelectedRow();

        if(selectedRow>-1){
            TableModelKorisnik tmk= (TableModelKorisnik) tblKorisnik.getModel();
            korisnik=tmk.getListItem(selectedRow);
            txtKorisnik.setText(korisnik.toString());
        }

    }//GEN-LAST:event_tblKorisnikMouseClicked

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        TableModelKnjiga tmk = (TableModelKnjiga) tblKnjiga.getModel();
        int selectedRow = tblKnjiga.getSelectedRow();
        if (selectedRow >= 0) {
            try {
                knjiga = tmk.getKnjiga(selectedRow);
                if(knjiga.getKolicina()<=0){
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da doda stavku.","Error",
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
                StavkaUsluge stavkaUsluge = new StavkaUsluge(usluga, -1, knjiga);

                TableModelStavke tms = (TableModelStavke) tblStavkeUsluge.getModel();
                System.out.println(tms);
                if (tms.getRowCount() > 0) {
                    if (tms.postojiKnjiga(knjiga)) {
                        JOptionPane.showMessageDialog(this, "Vec ste uneli ovu knjigu!","Error",JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                tms.dodajStavku(stavkaUsluge);
                tmk.smanjiKolicinu(selectedRow);

            } catch (Exception ex) {
                Logger.getLogger(FrmUpdateUsluga.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita stavku.","Error",
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed

        TableModelStavke tmStavke = (TableModelStavke) tblStavkeUsluge.getModel();
        int rowIndex = tblStavkeUsluge.getSelectedRow();
        if (rowIndex >= 0) {
            StavkaUsluge stavkaUsluge= tmStavke.getStavkaUsluge(rowIndex);
            knjiga=stavkaUsluge.getKnjiga();
            TableModelKnjiga tmk = (TableModelKnjiga) tblKnjiga.getModel();
            tmk.povecajKolicinu(knjiga);
            tmStavke.deleteStavka(rowIndex);

        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita stavku","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void txtKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKnjigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKnjigaActionPerformed

    private void txtKnjigaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKnjigaKeyReleased
        String parametar = txtKnjiga.getText();
        TableModelKnjiga tmKnjiga = (TableModelKnjiga) tblKnjiga.getModel();
        tmKnjiga.setParametar(parametar);
        if (tmKnjiga.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Sistem ne moze da nadje knjige po zadatoj vrednosti",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_txtKnjigaKeyReleased

    private void btnIzmeniUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniUsluguActionPerformed
        try {

            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            TableModelStavke tmStavke= (TableModelStavke) tblStavkeUsluge.getModel();

            Usluga u=new Usluga(usluga.getUslugaID(), sdf.parse(txtDatumOd.getText()), sdf.parse(txtDatumDo.getText()),
                korisnik, ulogovani, (ArrayList<StavkaUsluge>) tmStavke.getListaStavki());

            if(txtKorisnik.getText().isEmpty() || txtDatumOd.getText().isEmpty() ||
                txtDatumDo.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Sistem ne moze da izmeni uslugu","Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            if(tblStavkeUsluge.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Sistem ne moze da izmeni uslugu","Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            ClientController.getInstance().updateUsluga(u);
            ClientController.getInstance().updateKnjiga(knjiga);
            JOptionPane.showMessageDialog(this,"Sistem je izmenio uslugu");
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Sistem ne moze da izmeni uslugu","Error",
                JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmUpdateUsluga.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIzmeniUsluguActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzmeniUslugu;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JTable tblKnjiga;
    private javax.swing.JTable tblKorisnik;
    private javax.swing.JTable tblStavkeUsluge;
    private javax.swing.JFormattedTextField txtDatumDo;
    private javax.swing.JFormattedTextField txtDatumOd;
    private javax.swing.JTextField txtKnjiga;
    private javax.swing.JTextField txtKorisnik;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        try {
            SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yyyy");
            txtKorisnik.setText(korisnik.toString());
            txtDatumOd.setText(usluga.getDatumIzdavanja().toString());
            txtDatumDo.setText(usluga.getDatumIsteka().toString());
            tblKorisnik.setModel(new TableModelKorisnik());
            tblKnjiga.setModel(new TableModelKnjiga());
            TableModelStavke tmStavke=new TableModelStavke();
            tmStavke.setListaStavki(usluga.getListaStavki());
            tblStavkeUsluge.setModel(tmStavke);
        } catch (Exception ex) {
            Logger.getLogger(FrmUpdateUsluga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
