/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.korisnik;

import controller.ClientController;
import domain.Korisnik;
import form.FrmMain;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandra
 */
public class FrmUpdateKorisnik extends javax.swing.JDialog {
    private Korisnik korisnik;
    /**
     * Creates new form FrmEditUser
     */
    public FrmUpdateKorisnik(JFrame parent, boolean modal,Korisnik korisnik) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Azuriranje korisnika");
        txtPrezime.setText(korisnik.getPrezime());
        txtKontakt.setText(korisnik.getKontaktTelefon());
        this.korisnik=korisnik;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        txtKontakt = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Prezime:");

        jLabel3.setText("Kontakt:");

        txtPrezime.setText("jTextField1");

        txtKontakt.setText("jTextField1");

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(txtKontakt, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIzmeni)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            if (txtKontakt.getText().isEmpty() || txtPrezime.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da izmeni korisnika!","Error",
                        JOptionPane.ERROR_MESSAGE);
            return;
            }
            if (!txtKontakt.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(this,"Sistem ne moze da izmeni korisnika","Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(txtKontakt.getText().length()<6){
                JOptionPane.showMessageDialog(this,"Sistem ne moze da izmeni korisnika","Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            Korisnik k= new Korisnik();
            k.setKorisnikID(korisnik.getKorisnikID());
            k.setPrezime(txtPrezime.getText());
            k.setKontaktTelefon(txtKontakt.getText());
            
            ClientController.getInstance().updateKorisnik(k);
            JOptionPane.showMessageDialog(this,"Sistem je izmenio korisnika");
            
            FrmMain main = (FrmMain) getParent();
	    main.refreshTableKorisnik();
            
        } catch (Exception ex) {
            Logger.getLogger(FrmUpdateKorisnik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtKontakt;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
