/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import communication.Communication;
import form.components.TableModelKnjiga;
import form.components.TableModelKorisnik;
import form.components.TableModelStavke;
import controller.ClientController;
import domain.Bibliotekar;
import domain.Knjiga;
import domain.Korisnik;
import domain.StavkaUsluge;
import domain.Usluga;
import form.knjiga.FrmAddKnjiga;
import form.knjiga.FrmUpdateKnjiga;
import form.korisnik.FrmAddKorisnik;
import form.korisnik.FrmUpdateKorisnik;
import form.usluga.FrmFindUsluga;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandra
 */
public class FrmMain extends javax.swing.JFrame {
    Bibliotekar ulogovani;
    Korisnik korisnik;
    Knjiga knjiga;
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Glavna klijentska forma");
        this.ulogovani= Communication.getInstance().getUlogovani();
        lblUlogovani.setText("Ulogovani: "+ulogovani);    
        
        tblKorisnik.setModel(new TableModelKorisnik());
        
        tblKnjiga.setModel(new TableModelKnjiga());
        
        tblStavkeUsluge.setModel(new TableModelStavke());
        
        refreshTableKorisnik();
        refreshTableKnjiga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDatumOd = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDatumDo = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKorisnik = new javax.swing.JTable();
        btnIzmeniKorisnika = new javax.swing.JButton();
        btnObrisiKorisnika = new javax.swing.JButton();
        txtKorisnik = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeUsluge = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtKnjiga = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKnjiga = new javax.swing.JTable();
        btnIzmeniKnjigu = new javax.swing.JButton();
        lblUlogovani = new javax.swing.JLabel();
        btnSacuvajUslugu = new javax.swing.JButton();
        mbMain = new javax.swing.JMenuBar();
        mKorisnik = new javax.swing.JMenu();
        miNoviKorisnik = new javax.swing.JMenuItem();
        mKnjiga = new javax.swing.JMenu();
        miDodajKnjigu = new javax.swing.JMenuItem();
        mUsluga = new javax.swing.JMenu();
        miIzmeniUslugu = new javax.swing.JMenuItem();
        mOdjava = new javax.swing.JMenu();
        miOdjava = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenuItem3.setText("jMenuItem3");

        jMenu4.setText("jMenu4");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usluga"));

        jLabel1.setText("Izabrani korisnik:");

        jLabel3.setText("Datum od:");

        txtDatumOd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumOd.setText("01.09.2023");

        jLabel4.setText("Datum do:");

        txtDatumDo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumDo.setText("21.09.2023");
        txtDatumDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumDoActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga korisnika"));

        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        tblKorisnik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKorisnik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKorisnikMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKorisnik);

        btnIzmeniKorisnika.setText("Izmeni izabranog korisnika");
        btnIzmeniKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniKorisnikaActionPerformed(evt);
            }
        });

        btnObrisiKorisnika.setText("Obriši korisnika");
        btnObrisiKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiKorisnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtPretraga)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnIzmeniKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnObrisiKorisnika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiKorisnika)
                    .addComponent(btnIzmeniKorisnika))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavka usluge"));

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Obrisi stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        tblStavkeUsluge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkeUsluge);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga knjige"));

        txtKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKnjigaActionPerformed(evt);
            }
        });
        txtKnjiga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKnjigaKeyReleased(evt);
            }
        });

        tblKnjiga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblKnjiga);

        btnIzmeniKnjigu.setText("Izmeni knjigu");
        btnIzmeniKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniKnjiguActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKnjiga, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzmeniKnjigu)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzmeniKnjigu)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajStavku)
                    .addComponent(btnObrisiStavku))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnDodajStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisiStavku)
                        .addGap(31, 31, 31))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKorisnik)
                            .addComponent(txtDatumDo)
                            .addComponent(txtDatumOd))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblUlogovani.setText("Ulogovani:");

        btnSacuvajUslugu.setText("Sacuvaj uslugu");
        btnSacuvajUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajUsluguActionPerformed(evt);
            }
        });

        mKorisnik.setText("Korisnik");

        miNoviKorisnik.setText("Novi korisnik");
        miNoviKorisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviKorisnikActionPerformed(evt);
            }
        });
        mKorisnik.add(miNoviKorisnik);

        mbMain.add(mKorisnik);

        mKnjiga.setText("Knjiga");

        miDodajKnjigu.setText(" Nova knjiga");
        miDodajKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDodajKnjiguActionPerformed(evt);
            }
        });
        mKnjiga.add(miDodajKnjigu);

        mbMain.add(mKnjiga);

        mUsluga.setText("Usluga");

        miIzmeniUslugu.setText("Upravljaj uslugom");
        miIzmeniUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIzmeniUsluguActionPerformed(evt);
            }
        });
        mUsluga.add(miIzmeniUslugu);

        mbMain.add(mUsluga);

        mOdjava.setText("Odjava");

        miOdjava.setText("Odjavi se");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        mOdjava.add(miOdjava);

        mbMain.add(mOdjava);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUlogovani)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(btnSacuvajUslugu, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvajUslugu)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNoviKorisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviKorisnikActionPerformed
        new FrmAddKorisnik(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviKorisnikActionPerformed

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased
        String parametar = txtPretraga.getText();
        TableModelKorisnik tmKorisnik = (TableModelKorisnik) tblKorisnik.getModel();
        tmKorisnik.setParametar(parametar);
        if (tmKorisnik.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Sistem ne moze da nadje korisnike po zadatoj vrednosti",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_txtPretragaKeyReleased

    private void btnIzmeniKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniKorisnikaActionPerformed
        int rowIndex=tblKorisnik.getSelectedRow();
        if(rowIndex>=0){
            TableModelKorisnik tm=(TableModelKorisnik) tblKorisnik.getModel();
            Korisnik korisnik= tm.getKorisnik(rowIndex);
            JOptionPane.showMessageDialog(this,"Sistem je ucitao korisnika.");
            new FrmUpdateKorisnik(this, true,korisnik).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"Sistem ne moze da ucita korisnika","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniKorisnikaActionPerformed

    private void btnObrisiKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiKorisnikaActionPerformed
      
        TableModelKorisnik tmKorisnik = (TableModelKorisnik) tblKorisnik.getModel();
        int rowIndex = tblKorisnik.getSelectedRow();
        if (rowIndex >= 0) {
            int deleteYesNo = JOptionPane.showConfirmDialog(this,
                    "Da li ste sigurni da zelite da obrisete ovog korisnika?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

            if (deleteYesNo == JOptionPane.NO_OPTION) {
                return;
            }

            if (deleteYesNo == JOptionPane.YES_OPTION) {
                try {
                    Korisnik korisnik = tmKorisnik.getKorisnik(rowIndex);
                    ClientController.getInstance().deleteKorisnik(korisnik);
                    refreshTableKorisnik();
                    JOptionPane.showMessageDialog(this, "Sistem je obrisao korisnika.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise korisnika", "Error", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise korisnika", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiKorisnikaActionPerformed

    private void tblKorisnikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKorisnikMouseClicked
        int selectedRow=tblKorisnik.getSelectedRow();
        
        if(selectedRow>-1){
            TableModelKorisnik tmk= (TableModelKorisnik) tblKorisnik.getModel();
            korisnik=tmk.getListItem(selectedRow);
            txtKorisnik.setText(korisnik.toString());
        }
        
    }//GEN-LAST:event_tblKorisnikMouseClicked

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        TableModelKnjiga tmk = (TableModelKnjiga) tblKnjiga.getModel();
        int selectedRow = tblKnjiga.getSelectedRow();
        if (selectedRow >= 0) {
            try {
                knjiga = tmk.getKnjiga(selectedRow);
                if(knjiga.getKolicina()<=0){
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da doda stavku.","Error",
                    JOptionPane.ERROR_MESSAGE);
                    return;
                }
                StavkaUsluge stavkaUsluge = new StavkaUsluge(null, -1, knjiga);
                
                TableModelStavke tms = (TableModelStavke) tblStavkeUsluge.getModel();
                if (tms.getRowCount() > 0) {
                    if (tms.postojiKnjiga(knjiga)) {
                        JOptionPane.showMessageDialog(this, "Vec ste uneli ovu knjigu!","Error",JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                tms.dodajStavku(stavkaUsluge);
                tmk.smanjiKolicinu(selectedRow);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita stavku.", "Error", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita stavku.","Error",
                    JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        
        TableModelStavke tmStavke = (TableModelStavke) tblStavkeUsluge.getModel();
        int rowIndex = tblStavkeUsluge.getSelectedRow();
        if (rowIndex >= 0) {
            StavkaUsluge stavkaUsluge= tmStavke.getStavkaUsluge(rowIndex);
            knjiga=stavkaUsluge.getKnjiga();
            TableModelKnjiga tmk = (TableModelKnjiga) tblKnjiga.getModel();
            tmk.povecajKolicinu(knjiga);
            tmStavke.deleteStavka(rowIndex);
            
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise stavku","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnSacuvajUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajUsluguActionPerformed
        try {
            
            if(txtKorisnik.getText().isEmpty() || txtDatumOd.getText().isEmpty() || 
                    txtDatumDo.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Sistem ne moze da kreira uslugu","Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            /*if(tblStavkeUsluge.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Sistem ne moze da kreira uslugu","Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }*/
            
            
            
            SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yyyy");
            
            /*if(sdf.parse(txtDatumOd.getText()).after(sdf.parse(txtDatumDo.getText()))){
                JOptionPane.showMessageDialog(this,"Sistem ne moze da kreira uslugu","Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }*/
            
            TableModelStavke tmStavke= (TableModelStavke) tblStavkeUsluge.getModel();
            
            Usluga usluga=new Usluga(null, sdf.parse(txtDatumOd.getText()), sdf.parse(txtDatumDo.getText()),
                    korisnik, ulogovani, (ArrayList<StavkaUsluge>) tmStavke.getListaStavki());
            
            ClientController.getInstance().addUsluga(usluga);
            ClientController.getInstance().updateKnjiga(knjiga);
            JOptionPane.showMessageDialog(this,"Sistem je kreirao uslugu");
            resetForm();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Sistem ne moze da kreira uslugu","Error",
                    JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_btnSacuvajUsluguActionPerformed

    private void miDodajKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDodajKnjiguActionPerformed
        new FrmAddKnjiga(this, true).setVisible(true);
    }//GEN-LAST:event_miDodajKnjiguActionPerformed

    private void miIzmeniUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIzmeniUsluguActionPerformed
        new FrmFindUsluga(this, true).setVisible(true);
    }//GEN-LAST:event_miIzmeniUsluguActionPerformed

    private void txtKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKnjigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKnjigaActionPerformed

    private void txtKnjigaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKnjigaKeyReleased
        String parametar = txtKnjiga.getText();
        TableModelKnjiga tmKnjiga = (TableModelKnjiga) tblKnjiga.getModel();
        tmKnjiga.setParametar(parametar);
        if (tmKnjiga.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Sistem ne moze da nadje knjige po zadatoj vrednosti",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_txtKnjigaKeyReleased

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
	    new FrmLogin().setVisible(true);
	    Communication.getInstance().setUlogovani(null);
            this.dispose();
        }
    }//GEN-LAST:event_miOdjavaActionPerformed

    private void btnIzmeniKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniKnjiguActionPerformed
        int selectedRow = tblKnjiga.getSelectedRow();
        if (selectedRow >= 0) {
            TableModelKnjiga tm=(TableModelKnjiga) tblKnjiga.getModel();
            Knjiga k=tm.getKnjiga(selectedRow);
            JOptionPane.showMessageDialog(this,"Sistem je ucitao knjigu.");
            new FrmUpdateKnjiga(this, true,k).setVisible(true);
        }else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita knjigu","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnIzmeniKnjiguActionPerformed

    private void txtDatumDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumDoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumDoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzmeniKnjigu;
    private javax.swing.JButton btnIzmeniKorisnika;
    private javax.swing.JButton btnObrisiKorisnika;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnSacuvajUslugu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenu mKnjiga;
    private javax.swing.JMenu mKorisnik;
    private javax.swing.JMenu mOdjava;
    private javax.swing.JMenu mUsluga;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JMenuItem miDodajKnjigu;
    private javax.swing.JMenuItem miIzmeniUslugu;
    private javax.swing.JMenuItem miNoviKorisnik;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JTable tblKnjiga;
    private javax.swing.JTable tblKorisnik;
    private javax.swing.JTable tblStavkeUsluge;
    private javax.swing.JFormattedTextField txtDatumDo;
    private javax.swing.JFormattedTextField txtDatumOd;
    private javax.swing.JTextField txtKnjiga;
    private javax.swing.JTextField txtKorisnik;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    public void refreshTableKorisnik() {
        TableModelKorisnik tmKorisnik= (TableModelKorisnik) tblKorisnik.getModel();
        tmKorisnik.refreshTable();
    }
    
    public void refreshTableKnjiga() {
        TableModelKnjiga tmKnjiga= (TableModelKnjiga) tblKnjiga.getModel();
        tmKnjiga.refreshTable();
    }
    
    private void resetForm() {
        txtKorisnik.setText("");
        txtDatumOd.setText("");
        txtDatumDo.setText("");
	TableModelStavke tmStavke = (TableModelStavke) tblStavkeUsluge.getModel();
        tmStavke.getListaStavki().clear();
        tmStavke.fireTableDataChanged();
    }

 

    
}
